### ISSUE TITLE
The duration of the experiment

### ISSUE THREAD

**Issue by yori1002** [laquabe/OneNet#4]
Hello, may I ask what the hardware requirements are for the experiment? And how much GPU memory does it occupy? Additionally, how long does the reasoning and testing process take respectively?

**Comment by laquabe** [comment]
Hi, since we run each module in steps, we will not use many GPUs at the same time. Each step only requires one 3090 or 4090. 
In terms of time efficiency, the time consumed varies for different modules. Roughly speaking, each module takes about several seconds or less to reason about one piece of data at a time. However, some modules have particularly large amounts of data (e.g., Candidate Entity Filter, which may take a few weeks for some large datasets), so we suggest conducting experiments with the intermediate results we released first.
